### ISSUE TITLE
Can't use in ipython!!!! 

### ISSUE THREAD

**Issue by PAHTNOM233** [DanGill/scprint#1]
this module only can use in normal python console, can't use in ipython !

**Comment by DanGill** [comment]
This is because of IPython's 4-bit colour limitation (16 total colours)

SCPrint uses a 16-bit colour system (256 total colours) and is therefore incompatible.
It would be possible to create a new `color.py` file to translate the 4-bit colour names into there corresponding 4-bit ANSI escape sequences. I may add a 4-Bit compatibility mode to the module in the future.

Unfortunately, they would be no other way around this at the moment.

Consider using another python module such as [colorama](https://pypi.org/project/colorama/).
